services:
  tradoge:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3