version: 0.1
twitter:
  # These tokens can be found in the cookies of your browser :
  # F12 or right click -> Inspect
  # On Chrome browsers: Application -> Cookies -> https://x.com
  # On Firefox: Storage -> Cookies -> https://x.com
  tokens:
    # Twitter (X) authToken in cookies
    authToken:
    # Twitter (X) ctO token in cookies
    ct0:
  requestDelaySeconds: 20
exchangeAccount:
  accountName: binance
  exchangeName: binance-margin
  apiCredentials:
    # Binance API key with access to margin trading and your IP address authorized
    key:
    # Binance private key
    secret:
tradingPairs:
  - baseCurrency: DOGE
    quoteCurrency: USDC
    exchangeAccountName: binance
    searchKeywords:
      - doge
      - dogecoin
    includeReplies: false
    sellDelayMinutes: 5
# Optional
# URL for services that can notify you if the bot has an error (like betterstack.com, uptimerobot.com,
#  healthchecks.io ...)
heartbeatURL: